[server]
headless = true
address = "localhost"
port = 5000

[theme]
primaryColor = "#ff4b4b"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#31333F"
textColor = "#fafafa"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[global]
disableWatchdogWarning = true